CodeTable::EnglishLevel:
  - '专业英语八级'
  - '大学英语六级'
  - '大学英语二级'
  - '大学英语三级'
  - '大学英语四级'
  - '公共英语二级'
  - '公共英语三级'
  - '应用英语A级'
  - '应用英语B级'
  - '雅思'

CodeTable::EducationBackground:
  - '大专以下'
  - '大专'
  - '全日制本科'
  - '非全日制本科'
  - '研究生'

CodeTable::Channel:
  - '管理'
  - '机务'
  - '营销'
  - '飞行'
  - '空勤'
  - '服务A'
  - '服务B'
  - '服务C-1'
  - '信息'
  - '服务C-2'
  - '服务C-3'
  - '服务C-驾驶'
  - '航务航材'

Employee::JobTitle:
  - '会计师'
  - '政工师'
  - '一级飞行员'
  - '二级飞行员'
  - '三级飞行员'
  - '国际商务师'
  - '经济师'
  - '工程师'
  - '副译审'
  - '统计师'
  - '二级通信员'
  - '助教'
  - '二级领航员'
  - '二级机械员'
  - '三级机械员'
  - '翻译'
  - '三级领航员'
  - '注册安全工程师'
  - '助理经济师'
  - '主治医师'
  - '副主任医师'
  - '主管技师'
  - '助理'
  - '高级经济师'
  - '助理工程师'
  - '高级工程师'

Employee::JobTitleDegree:
  - '高级'
  - '中级'
  - '初级'

CodeTable::Location:
  - '北京'
  - '上海'
  - '重庆'
  - '昆明'
  - '广州'
  - '济南'
  - '深圳'
  - '西安'
  - '杭州'
  - '三亚'
  - '哈尔滨'
  - '长春'
  - '青岛'
  - '乌鲁木齐'
  - '宁波'
  - '南宁'
  - '海口'
  - '西宁'
  - '拉萨'
  - '长沙'
  - '贵阳'
  - '南京'
  - '温州'
  - '南昌'
  - '厦门'
  - '沈阳'
  - '大连'
  - '银川'
  - '兰州'
  - '郑州'
  - '武汉'
  - '西昌'
  - '呼和浩特'
  - '太原'
  - '徐州'
  - '常州'
  - '石家庄'
  - '桂林'
  - '九寨'
  - '合肥'
  - '天津'

Employee::LaborRelation:
  - '合同'
  - '合同制'
  - '合同制（协议）'
  - '集团派驻'
  - '南航派驻'
  - '集团借调'
  - '劳务协议'
  - '骐骥劳务'
  - '骐骥劳务（协议）'
  - '骐骥劳务（实习）'
  - '蓝天劳务'
  - '蓝天劳务（协议）'
  - '蓝天劳务（实习）'
  - '公务员'

Employee::DutyRank:
  - '公司正职'
  - '公司副职'
  - '总师/总监'
  - '总助职'
  - '一正'
  - '二正'
  - '二副级'
  - '一副'
  - '二副'
  - '一副级'
  - '分公司级'
CodeTable::WorkflowState:
  - '已生效'
  - '已撤销'
  - '已驳回'
  - '已审批'
  - '审批中'
