defaults: &defaults
  grade:
    validate_rule:
      scal: [branch_company, positive, deputy]
      branch_company: [positive, deputy, secondly_positive]
      positive: [deputy, secondly_positive]
      deputy: [secondly_positive]

  upload_image_extension: ['jpg', 'jpeg', 'gif', 'png', 'bmp']
  upload_excel_extension: ['xls', 'xlsx']
  upload_attachment_extension: ['exe']

  company_no: '006646'

  single_system_ip: '192.1.1.148'
  valid_trust_code: 'http://172.18.8.168:10000/SINGPOINT/services/TrustCodeValidator?wsdl'
  vaild_effect_user: 'http://172.18.8.168:10000/SINGPOINT/services/ValidEffectUser?wsdl'
  system_name: 'hrms'
  singpoint_sys_name: "川航人力资源系统"

  enum_permit:
    department_grades: "CodeTable::DepartmentGrade.all.where.not(level: 0)"
    department_natures: "CodeTable::DepartmentNature.all"
    channels: "CodeTable::Channel.all"
    categories: "CodeTable::Category.all"
    position_schedules: "Schedule.all"
    education_backgrounds: "CodeTable::EducationBackground.all"
    degrees: "CodeTable::Degree.all"
    genders: "CodeTable::Gender.all"
    marital_status: "CodeTable::MaritalStatus.all"
    english_levels: "CodeTable::EnglishLevel.all"
    labor_relations: "Employee::LaborRelation.all"
    employment_status: "Employee::EmploymentStatus.all"
    position_natures: "CodeTable::PositionNature.all"
    political_status: "CodeTable::PoliticalStatus.all"
    job_title_degrees: "Employee::JobTitleDegree.all"
    job_types: "Employee::JobType.all"
    duty_ranks: "Employee::DutyRank.all"
    workflow_state: "CodeTable::WorkflowState.all"

  enum_type:
    grade_id: 'department_grades'
    nature_id: 'department_natures'
    channel_id: 'channels'
    category_id: 'categories'
    schedule_id: 'position_schedules'
    education_background_id: 'education_backgrounds'
    degree_id: 'degrees'
    gender_id: 'genders'
    marital_status_id: 'marital_status'
    english_level_id: 'english_levels'
    labor_relation_id: 'labor_relations'
    employment_status_id: 'employment_status'
    position_nature_id : 'position_natures'
    political_status_id: 'political_status'
    job_title_degree_id: 'job_title_degrees'
    job_type_id: 'job_types'
    duty_rank_id: 'duty_ranks'

  enums:
    audit_status:
      '无需审核': 0
      '待审核': 1
      '通过': 2
      '不通过': 3

  query_rule:
    default_page:
        page: 1
        per_page: 20
    position:
      sql:
        position_ids: "positions.id in (?)"
        name: "positions.name like ?" #like
        department_id: "positions.department_id = ?"
        department_ids: "positions.department_id in (?)" #in
        age: "positions.age" #range(from to)
        channel_name: "channels.name like ?" #relation model"s column
        staffing_surpass: "(positions.budgeted_staffing - positions.employees_count)" #超编: 'true'
  daily_working_hours:
    morning: "09:00:00"
    afternoon: "13:30:00"
    afternoon_end: "17:00:00"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
